import { Injectable } from '@angular/core';
import { Product } from '../../models/product.interface';

@Injectable({
  providedIn: 'root'
})
export class ProductService {

  products: Product[] = [
    {id: 1, model: "Samsung 65AU7000", brand: "Samsung", color: "Black", category: "Television", imgUrl: 'assets/images/products/Samsung 65AU7000.jpg', inches: "65”", desc: "SAMSUNG 65” 4K UHD SAMSUNG SMART TV", features: ["SAMSUNG 65” 4K UHD SAMSUNG SMART TV,ALEXA VOICE CONTROL,Q-SYMPHONY,WI-FI,SMART CONNECTIVITY,VOICE ASSISTANT-AU7000-BLACK", "65” SCREN DISPLAY", "ALEXA VOICE CONTROL", "BUILT-IN VOICE ASSISTANT", "Q-SYMPHONY FOR SYNCRONISING WITH YOUR SAMSUNG COMPATIBLE HOMETHEATRE OR SOUNDBAR", "IN-BUILT WI-FI AND ETHERNET", "SMART CONNECTIVITY", "ONE REMOTE CONTROL", "NETFLIX", "YOUTUBE", "MIRACAST", "GOOGLE ASSISTANT", "APPLE AIRPLAY 2", "AMAZON PRIME VIDEO", "WEB BROWSER", "BLUETOOTH", "4K HDR", "4K ULTRA HD", "4K QUAD CORE PROCESSOR", "3,840 x 2,160 SCREEN RESOLUTION", "AIRSLIM DESIGN", "AMBIENT MODE", "SAMSUNG TV PLUS", "GAME MODE", "3 HMDI PORTS", "2 USB PORTS"], specs: ["65AU7000", "Egypt", "128X8X18", "25", "PVC"]},

    {id: 2, model: "Samsung 50CU7000", brand: "Samsung", color: "Black", category: "Television", imgUrl: 'assets/images/products/Samsung 50CU7000.jpg', inches: "50”", desc: "SAMSUNG 50″ Crystal UHD 4K Smart LED TV - 2023", features: ["50″ Crystal UHD 4K Smart LED TV", "DVB-T2 Digital Tuner Ready", "3840 x 2160 Resolution", "Crystal UHD Display", "Crystal Processor 4K", "Pur Colour", "HDR", "One Billion Colours", "50Hz Refresh Rate", "Contrast Ratio", "Micro UHD Dimming", "Contrast Enhancer", "Motion Xcelerator", "Slim Look Design, 3 Bezel-Less Design, Slim Lift Stand", "Picture Clarity", "Object Tracking Sound (OTS Lite)", "Q-Symphony", "Web Browser", "WiFi Direct", "Wireless LAN Built-in", "Anynet+ (HDMI-CEC)", "ConnectShare™ (USB 2.0) / Connect Share™ (HDD)", "3 x HDMI", "1 x USB", "1 x Component / AV Shared Input"], specs: ["50CU7000", "Egypt", "14.3", "14", "PVC"]},

    {id: 3, model: "Sony 55A80J", brand: "Sony", color: "Black", category: "Television", imgUrl: 'assets/images/products/Sony 55A80J.jpg', inches: "55”", desc: "Sony BRAVIA XR OLED 4K Ultra HD HDR Smart Google TV - 2022", features: ["SONY 55''OLED 4K ANDROID TV", "4K ULTRA HD ANDROID TV", "OLED ANDROID TV", "WIFI CERTFIFIED", "DISPLAY RESOLUTION: 3840 x 2160", "4K HDR (HIGH DYNAMIC RANGE) COMPATIBILITY", "PICTURE PROCESSOR X1™ Ultimate", "4K X-REALITY™ PRO", "TRILUMINOS™ Display", "DTS DIGITAL SURROUND", "VOICE SEARCH", "OPERATING SYSTEM: Android™", "ON-BOARD STORAGE (GB): 16GB", "INTERNET BROWSER", "X-Motion Clarity™", "Object-based HDR remaster", "Acoustic Surface Audio", "S-Force Front Surround", "Voice Zoom", "Unique ambient optimisation technology", "Cable clutter minimised", "Over 5000 apps, more than any other smart TV", "Netflix", "Connect with your Alexa", "Google Assistant", "Send to a bigger, better screen with Chromecast", "Works with Google Home", "Works with Apple AirPlay / Apple HomeKit", "Clear Phase", "Easy control with smart remote", "Dolby Vision™", "Bluetooth connectivity", "Netflix Calibrated Mod", "HDMI INPUT: 4", "USB PORTS: 3"], specs: ["55A80J", "Malaysia", "16.6", "14", "PVC"]},

    {id: 4, model: "LG 65NANO776QA", brand: "LG", color: "Silver", category: "Television", imgUrl: 'assets/images/products/LG 65NANO776QA.jpg', inches: "65”", desc: "LG 65” NANO77 NANOCELL 4K Active HDR TV", features: ["NanoCell TV", "65 INCH", "4K (3840 x 2160)", "webOS", "Nano77 Series", "3 x HDMI", "2 x USB", "Real 4K NanoCell for Pure coloer with Nano Color , Nano Accuracy", "α5 Gen5 AI Processor 4k with AI 4K upscaling", "ThinQ AI webOS Smart TV with NFC Magic Remote", "True Cinema Experience suported with Active HDR , Film Maker Mode , AI Sound", "Unlimited Gameplay with HGiG , ALLM , HDMI 2.0 eARC"], specs: ["65NANO776QA", "Malaysia", "1235 x 774 x 232 mm", "26", "PVC"]},

    {id: 5, model: "Samsung Galaxy S10", brand: "Samsung", color: "Black", category: "phones and tablets", imgUrl: 'assets/images/products/Samsung Galaxy S10.jpg', inches: "6.1”", desc: "Samsung Galaxy S10 6.1” 128GB ROM + 8GB RAM - Single SIM Android SmartPhone", features: ["Display size: 6.1” Super AMOLED", "Memory: 128GB, 8GB RAM", "OS : Android 9.0 (Pie)", "Camera: 12MP + 12MP + 16MP Main Camera, 10MP Front Camera", "SIM: Single SIM", "Battery: Non-removable Li-Ion 3400 mAh battery", "Network: 4G,3G,2G"], specs: ["Model: S10 G973U", "Production Country: Vietnam", "Weight (kg): 0.5", "Main Material: Glass front, aluminium frame, Glass Back"]},

    {id: 6, model: "Nokia C32", brand: "Nokia", color: "Charcoal", category: "phones and tablets", imgUrl: 'assets/images/products/Nokia C32.jpg', inches: "6.5”", desc: "Nokia C32, 6.5” Display, 64GB ROM + Up To 7GB RAM, (Dual Sim), 50MP Camera Android SmartPhone", features: ["6.5 Inches", "Unisoc SC9863A (28nm)", "OS-Android 12", "3&2GB RAM", "64GB storage", "Back: 50 MP, (wide), AF 2 MP, (macro)", "Front:  8 MP", "Li-Po Li-Po 5000 mAh, non-removable"], specs: ["Model: C32", "Weight (kg): 0.1995"]},

    {id: 7, model: "Apple IPhone 14 Pro Max", brand: "Apple", color: "Gold", category: "phones and tablets", imgUrl: 'assets/images/products/14 Pro Max.jpg', inches: "6.7”", desc: "Apple IPhone 14 Pro Max, 6.7”, 256GB + 6GB RAM (Single SIM), 4323mAh, 5G", features: ["Display: 6.7” LTPO Super Retina XDR OLED", "Memory: 128GB + 6GB RAM", "Chip: A16 Bionic chip", "Pro 12MP camera", "Wireless charging up to 15W", "12MP True Depth Camera", "4K video recording", "OS: iOS 16, upgradable to iOS 16.0.3", "Battery: 4323mAh"], specs: ["Model: A2894", "Weight (kg): 0.203"]},

    {id: 8, model: "Tecno Phantom V Flip", brand: "Tecno", color: "Iconic Black", category: "phones and tablets", imgUrl: 'assets/images/products/Phantom V Flip.jpg', inches: "6.9”", desc: "Tecno Phantom V Flip 6.9” 5G, 256GB + 8GB RAM (Single SIM) 4000mAh, Iconic Black", features: ["Main Display: 6.9” AMOLED", "Cover Screen: 1.32” Circular AMOLED", "Memory: 8GB RAM + 256GB", "Rear Camera: 64MP + 13MP", "Selfie Camera: 32MP", "Battery: 4000mAh, 45W Fast Charging"], specs: ["Model: V Flip", "Weight (kg): 0.192"]},

    {id: 9, model: "Samsung Galaxy Tab A7 Lite", brand: "Samsung", color: "Gray", category: "phones and tablets", imgUrl: 'assets/images/products/Galaxy Tab A7 Lite.jpg', inches: "8.7”", desc: "Samsung Galaxy Tab A7 Lite - 8.7” 32GB+3GB RAM", features: ["8.7-inch FHD+ TFT Display", "32GB Storage, 3 GB RAM", "8 MP Back Camera, 2 MP Front Camera", "Octa-core CPU: 4x2.3 GHz + 4x1.8 GHz", "Li-Ion 5100 mAh Battery", "OS: Android 11, One UI 3.1"], specs: ["Model: SM-T220", "Weight (kg): 2.2"]},

    {id: 10, model: "Lenovo Tab M10 Tablet", brand: "Lenovo", color: "Gray", category: "phones and tablets", imgUrl: 'assets/images/products/Lenovo Tab M10.jpg', inches: "10.1”", desc: "Lenovo Tab M10 HD TB-X306NC Tablet 10.1 Inch 4GB+64GB Android 10.0", features: ["CPU: MediaTek Helio P22T Octa-core", "Display: 10.1 inch 1280 x 800 pixel screen", "Memory: 4GB RAM + 64GB ROM", "Camera: 5MP front camera + 8MP back camera", "System: Android 10.0", "Battery: 7000mAh", "Network:  4G LTE, BT, Wifi", "Bluetooth:  V5.0"], specs: ["Model: TB-X306NC", "Weight (kg): 0.9"]},

    {id: 11, model: "Pro 11 3G Tablet PC", brand: "Pro", color: "Black", category: "phones and tablets", imgUrl: 'assets/images/products/Pro 11.jpg', inches: "10.1”", desc: "Pro 11 3G Tablet PC, 10.1 inch 2GB+32GB Android 5.1", features: ["Android 5.1 OS", "MTK6592 octa core processor", "RAM 2GB + ROM 32GB", "10.1 inch IPS screen, 1280x800 pixel", "Support dual SIM, BT, WiFi, G P S, FM", "0.3MP front camera and 2MP rear camera", "Built-in 4000mAh battery", "Multi-function: Full screen, dual SIM, Wifi, G P S, gravity sensor, alarm, calendar, calculator, audio recorder, video recorder, WAP/MMS/GPRS, image viewer, E-book, world clock, tasks card, rear flash, IML rear cover", "Frequency band:2G GSM 850/900/1800/1900MHz 3G WCDMA 850/2100MHz"], specs: ["Model: B16570AIZ=WMC0953B", "Production Country: China", "Size (L x W x H cm): 30 x 20 x 6cm", "Weight (kg): 1.00", "Main Material: Multi-Material"]},

    {id: 12, model: "Android Tablet", brand: "Android", color: "Black", category: "phones and tablets", imgUrl: 'assets/images/products/Android Tablet.jpg', inches: "10.1”", desc: "10.1 Inch Android Tablet 1GB RAM 16GB With SIM Card Slot GPS", features: ["CPU 1.3GHz, Android 4.4 OS", "10 inch /10.1 inch 1280*800 display screen", "RAM: 1GB / Hard-Drive Capacity (ROM): 16GB", "Cameras: 2MP Front Camera, 5MP Rear Camera", "Phone Call Function: Dual SIM Card Slots allow 2SIM cards can stay at the same time", "2G Network: Built-in 2G Module, support GSMNetwork, frequency range: GSM 850/900/1800/1900 MHz", "3G Network: Built-in 3G Module, support WCDMAGSM, frequency range: WCDMA 2100/850/1900 MHz", "Build-in a 3.7V/5000mAh rechargeable Li-Polymerbattery, running time more than 4 hours", "Power Adapter: CE certified AC Charger (INPUT100-240V, OUTPUT 5V 2A)", "Wireless Connection: Wi-Fi (Built-in 802.11b/g/nWLAN Card) Support 2.4GHz Wifi Network, Don't Support 5GHz WIFI Network", "Support Bluetooth GPS G-Sensor,built-in MIC & Speaker", "USB Port: 1 Micro USB port for charging &data transfer, 1 Audio Port: 3.5mm stereo Headphone jack", "Extend Card Slot: 1 TF Card slot available"], specs: ["Model: TLkt107","Dimension: 9.53*6.77*0.43 in (H*W*D)", "Weight (kg): 1", "Main Material: PVC"]},

    {id: 13, model: "HP EliteBook 840 G5", brand: "Hp", color: "Silver", category: "laptops", imgUrl: 'assets/images/products/EliteBook 840 G5.jpg', inches: "14”", desc: "HP EliteBook 840 G5 Intel Core I5 8th Gen 16GB RAM 512GB SSD 14 Inches FHD Display", features: ["Operating system: Windows 10 / 11 Pro – 64 Bit Edition", "Memory: 16GB DDR4 – 2400MHz SDRAM - Supports up to 32 GB", "Storage: 512GB PCIe® NVMe™ M.2 SSD", "Graphics Processor: Integrated: Intel® UHD Graphics 620", "Processor: Intel® Core™ i5-8350U vPro™ (1.7 GHz base frequency, up to 3.6 GHz with Intel® Turbo Boost Technology, 6 MB cache, 4 cores)", "Processor Family: 8th Generation Intel® Core™ i5 processor", "Display: 14 inches (35.56 cm) diagonal FHD IPS anti-glare LED-backlit, 220 cd/m², 67% sRGB (1920 x 1080)"], specs: ["Model: 840 G5", "Size (L x W x H cm): 32.6CM X 23.4CM X1.79CM", "Weight (kg): 1.48", "Main Material: ALUMINIUM"]},

    {id: 14, model: "DELL Latitude 7280", brand: "Dell", color: "Black", category: "laptops", imgUrl: 'assets/images/products/Latitude 7280.jpg', inches: "12.5”", desc: "DELL Latitude 7280 Intel Core I5- 2.5GHz 8GB RAM 256GB SSD Win10", features: ["Processor: intel core i5 (7th Gen Series) – 2.4Ghz", "Screen size 12.5 inches Full HD Screen", "RAM;8GB DDR4 RAM", "Storage: 256GB SSD", "Operating system: Win10 Pro", "Features: Wifi, Bluetooth, Built-in Microphone, Built-in Webcam"], specs: ["Model: 7280", "Weight (kg): 2.5", "Main Material: PVC"]},

    {id: 15, model: "DELL Optiplex 3000", brand: "Dell", color: "Black", category: "desktops", imgUrl: 'assets/images/products/Optiplex 3000.jpg', inches: "19.5”", desc: "DELL Optiplex 3000-12th Gen Intel Core I5-12500-8GB RAM+256GB SSD-Windows 19.5 inch Monitor", features: ["Display: 19.5 inch Monitor", "Processor: 12th Generation Intel Core i5-12500", "Storage: 256GB SSD", "Memory: 8GB RAM", "OS: Windows 11 Pro", ""], specs: ["Model: Optiplex 3000", "Size (L x W x H cm): 32.43 x 29.22 x 15.4", "Weight (kg): 5.17"]},
  ];

  constructor() { }

}
